import {
  createReadStream,
  existsSync,
  mkdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { dirname, normalize, relative, resolve } from 'node:path';
import { defineConfig, type Plugin } from 'vite';

const MIME: Record<string, string> = {
  '.webp': 'image/webp',
  '.glb': 'model/gltf-binary',
  '.m4a': 'audio/mp4',
  '.json': 'application/json',
};

/**
 * `pnpm dev` only: serves the MK8 pipeline's output (`$MK8_OUT`, default `.mk8-out/`) at `/mk8/`,
 * so converted assets can be tried locally without copying them into `public/` (MK-95).
 * Anything not there falls through to `public/mk8/` (the fonts).
 */
function mk8Assets(): Plugin {
  const root = resolve(import.meta.dirname, process.env.MK8_OUT ?? '.mk8-out');
  return {
    name: 'mk8-assets',
    apply: 'serve',
    configureServer(server) {
      server.middlewares.use('/mk8/', (req, res, next) => {
        const path = normalize(decodeURIComponent((req.url ?? '').split('?')[0] ?? ''));
        const file = resolve(root, `.${path}`);
        if (!file.startsWith(root) || !existsSync(file) || !statSync(file).isFile()) return next();
        const type = MIME[file.slice(file.lastIndexOf('.'))];
        if (type) res.setHeader('Content-Type', type);
        createReadStream(file).pipe(res);
      });
    },
  };
}

/** The track editor's generated files start with this (`src/dev/trackEditor/serialize.ts`). */
const GENERATED_HEADER = '// Generated by the track editor (MK-100)';
const EDITOR_FILES = { route: 'route.ts', materials: 'materials.ts' } as const;

/**
 * `pnpm dev` only: `POST /__track-editor/save` `{ course, file: 'route' | 'materials', source }`
 * writes `src/mk8/content/courses/<course>/<file>.ts` for the track editor (MK-100), formatted with
 * Prettier. It never overwrites a file the editor didn't generate (test-ramp's hand-written route).
 */
function trackEditorSave(): Plugin {
  const courses = resolve(import.meta.dirname, 'src/mk8/content/courses');
  return {
    name: 'track-editor-save',
    apply: 'serve',
    configureServer(server) {
      server.middlewares.use('/__track-editor/save', (req, res) => {
        const reply = (status: number, body: object) => {
          res.statusCode = status;
          res.setHeader('Content-Type', 'application/json');
          res.end(JSON.stringify(body));
        };
        if (req.method !== 'POST') return reply(405, { error: 'POST only' });
        let raw = '';
        req.on('data', (chunk: Buffer) => (raw += chunk.toString()));
        req.on('end', () => {
          void (async () => {
            const { course, file, source } = JSON.parse(raw) as Record<string, unknown>;
            const name = EDITOR_FILES[file as keyof typeof EDITOR_FILES];
            if (typeof course !== 'string' || !/^[a-z0-9-]+$/.test(course) || !name)
              return reply(400, { error: 'Bad course or file' });
            if (typeof source !== 'string' || !source.startsWith(GENERATED_HEADER))
              return reply(400, { error: 'Not a track editor export' });
            const target = resolve(courses, course, name);
            if (existsSync(target) && !readFileSync(target, 'utf8').startsWith(GENERATED_HEADER))
              return reply(409, { error: `${name} is hand-written: download it instead` });
            const prettier = await import('prettier');
            const options = await prettier.resolveConfig(target);
            const formatted = await prettier.format(source, { ...options, filepath: target });
            mkdirSync(dirname(target), { recursive: true });
            writeFileSync(target, formatted);
            reply(200, { path: relative(import.meta.dirname, target) });
          })().catch((error: unknown) => reply(500, { error: String(error) }));
        });
      });
    },
  };
}

export default defineConfig({
  plugins: [mk8Assets(), trackEditorSave()],
  build: {
    target: 'es2022',
    // three.js alone is ~520 kB minified; the real budget (≤ 700 kB gzipped) is enforced in MK-28.
    chunkSizeWarningLimit: 800,
    rollupOptions: {
      input: {
        main: resolve(import.meta.dirname, 'index.html'),
        dev: resolve(import.meta.dirname, 'dev.html'),
        mk8Sprites: resolve(import.meta.dirname, 'dev/mk8-sprites.html'),
        trackEditor: resolve(import.meta.dirname, 'dev/track-editor.html'),
      },
    },
  },
});
