// The track editor's export (MK-100): a course's `route.ts` and `materials.ts` as TypeScript source,
// pure data in the repo's Prettier style (single quotes, trailing commas, 100 columns), so a
// download can be committed as is. Numbers are written exactly (`String(n)` round-trips), so
// loading an export gives back identical data; the editor rounds what it places, not this.
import type { MeshMaterialSurface } from '../../sim/meshCollision';
import type { RouteDef } from '../../sim/route';

/** First line of every generated file: the dev server only overwrites files that start with it. */
export const GENERATED_HEADER = '// Generated by the track editor (MK-100)';

const PRINT_WIDTH = 100;
const INDENT = '  ';
const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;

type Data = number | string | boolean | Data[] | { [key: string]: Data | undefined };

/** Single quotes, or double when that needs fewer escapes (as Prettier picks). */
function quote(s: string): string {
  const escaped = s
    .replace(/\\/g, '\\\\')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
  if (s.includes("'") && !s.includes('"')) return `"${escaped}"`;
  return `'${escaped.replace(/'/g, "\\'")}'`;
}
const key = (k: string) => (IDENTIFIER.test(k) ? k : quote(k));
const number = (n: number) => (Object.is(n, -0) ? '-0' : String(n));

/** One line if it fits after `used` columns, else one entry per line. */
function print(value: Data, depth: number, used: number): string {
  if (typeof value === 'number') return number(value);
  if (typeof value === 'string') return quote(value);
  if (typeof value === 'boolean') return String(value);
  const isArray = Array.isArray(value);
  const parts = isArray
    ? value.map((v) => print(v, depth + 1, 0))
    : Object.entries(value)
        .filter((e): e is [string, Data] => e[1] !== undefined)
        .map(([k, v]) => `${key(k)}: ${print(v, depth + 1, k.length + 2)}`);
  const [open, close] = isArray ? ['[', ']'] : ['{', '}'];
  if (parts.length === 0) return `${open}${close}`;
  const flat = isArray ? `[${parts.join(', ')}]` : `{ ${parts.join(', ')} }`;
  if (!flat.includes('\n') && used + depth * INDENT.length + flat.length < PRINT_WIDTH) return flat;
  const inner = INDENT.repeat(depth + 1);
  return `${open}\n${parts.map((e) => `${inner}${e},`).join('\n')}\n${INDENT.repeat(depth)}${close}`;
}

/** `src/mk8/content/courses/<courseId>/route.ts`. */
export function routeSource(route: RouteDef, courseId: string): string {
  const data: RouteDef = {
    points: route.points,
    checkpoints: route.checkpoints,
    respawnPoints: route.respawnPoints,
    gridSlots: route.gridSlots,
    itemBoxRows: route.itemBoxRows,
    coinLines: route.coinLines,
    zones: route.zones,
  };
  return [
    `${GENERATED_HEADER} for \`${courseId}\`: /dev/track-editor.html?course=${courseId}.`,
    '// Pure data (ADR 0010). Edit it in the editor and export again rather than by hand.',
    "import type { RouteDef } from '../../../../sim/route';",
    '',
    `export const route: RouteDef = ${print(data as unknown as Data, 0, 'export const route: RouteDef = '.length)};`,
    '',
  ].join('\n');
}

/** `src/mk8/content/courses/<courseId>/materials.ts`: material name → surface, sorted by name. */
export function materialsSource(
  materials: Record<string, MeshMaterialSurface>,
  courseId: string,
): string {
  const sorted = Object.fromEntries(
    Object.entries(materials).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)),
  );
  const entries = Object.entries(sorted).map(([k, v]) => `  ${key(k)}: ${quote(v)},`);
  const body = entries.length ? `{\n${entries.join('\n')}\n}` : '{}';
  return [
    `${GENERATED_HEADER} for \`${courseId}\`: material → collision surface overrides.`,
    "// `pnpm mk8:build` uses these before its name guesses; 'ignore' drops a material's triangles.",
    "import type { MeshMaterialSurface } from '../../../../sim/meshCollision';",
    '',
    `export const materials: Record<string, MeshMaterialSurface> = ${body};`,
    '',
  ].join('\n');
}
