-- Track limits for Frostpeak Pass after its QA round 2 layout (MK-59: S-bends, a chicane and two
-- snow kickers make the lap longer). Generated by `pnpm track-limits`; the other tracks' rows are
-- unchanged (0001_leaderboard.sql).
insert into public.track_limits (track_id, laps, min_race_ms, min_lap_ms) values
  ('frostpeak-pass', 3, 73833, 24611)
on conflict (track_id) do update set
  laps = excluded.laps, min_race_ms = excluded.min_race_ms, min_lap_ms = excluded.min_lap_ms;
