-- Track limits for Neon Harbour after its QA round 2 layout (MK-60: a longer lap with an S on
-- the quay and the old-town loop). Generated by `pnpm track-limits`; the other tracks' rows are
-- unchanged.
insert into public.track_limits (track_id, laps, min_race_ms, min_lap_ms) values
  ('neon-harbour', 3, 85536, 28512)
on conflict (track_id) do update set
  laps = excluded.laps, min_race_ms = excluded.min_race_ms, min_lap_ms = excluded.min_lap_ms;
