// Generated by the track editor (MK-100) for `thwomp-ruins`: material → collision surface overrides.
// `pnpm mk8:build` uses these before its name guesses; 'ignore' drops a material's triangles.
// Empty until the course is traced on the pack (MK-124: built without it; README.md).
import type { MeshMaterialSurface } from '../../../../sim/meshCollision';

export const materials: Record<string, MeshMaterialSurface> = {};
